#!/usr/bin/env bash
set -euo pipefail

WORKBENCH_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PUBLIC_DIR="${WORKBENCH_DIR}/public"
RELEASE_ID="${RELEASE_ID:-$(date -u +%Y-%m-%d)}"
OUT_DIR="${OUT_DIR:-${WORKBENCH_DIR}/dist/${RELEASE_ID}}"
STAGE_DIR="${OUT_DIR}/public"
SERVER_BASE_URL="${SERVER_BASE_URL:-}"
GITHUB_MANIFEST_URL="${GITHUB_MANIFEST_URL:-}"
SIGNING_KEY="${SIGNING_KEY:-}"
TRUST_RELEASE_MANIFEST_URL="${TRUST_RELEASE_MANIFEST_URL:-}"
TRUST_RELEASE_SIGNATURE_URL="${TRUST_RELEASE_SIGNATURE_URL:-}"
TRUST_PUBLIC_KEY_FILE="${TRUST_PUBLIC_KEY_FILE:-}"

RUNTIME_ASSETS=(
  index.html
  trust-config.js
  manifest.webmanifest
  sw.js
  css/app.css
  js/app.js
  js/workspace-db.js
  workers/singular-batch-worker.js
  workers/singular-terminal-worker.js
  vendor/versions.json
  vendor/xterm/xterm.css
  vendor/xterm/xterm.js
  vendor/xterm/addon-fit.js
  vendor/xterm-pty/index.mjs
  vendor/xterm-pty/workerTools.js
  engine/engine-manifest.json
  engine/Singular.js
  engine/Singular.wasm
  engine/Singular.data
)

mkdir -p "${OUT_DIR}"
rm -rf "${STAGE_DIR}"
mkdir -p "${STAGE_DIR}"
cp -R "${PUBLIC_DIR}/." "${STAGE_DIR}/"

for asset in "${RUNTIME_ASSETS[@]}"; do
  if [[ ! -f "${STAGE_DIR}/${asset}" ]]; then
    echo "Missing runtime asset: ${STAGE_DIR}/${asset}" >&2
    exit 1
  fi
done

if [[ -n "${TRUST_RELEASE_MANIFEST_URL}" || -n "${TRUST_RELEASE_SIGNATURE_URL}" || -n "${TRUST_PUBLIC_KEY_FILE}" ]]; then
  if [[ -z "${TRUST_RELEASE_MANIFEST_URL}" || -z "${TRUST_RELEASE_SIGNATURE_URL}" || -z "${TRUST_PUBLIC_KEY_FILE}" ]]; then
    cat >&2 <<MSG
Trusted browser verification needs all three variables:
  TRUST_RELEASE_MANIFEST_URL
  TRUST_RELEASE_SIGNATURE_URL
  TRUST_PUBLIC_KEY_FILE
MSG
    exit 1
  fi
  python3 - "${TRUST_RELEASE_MANIFEST_URL}" "${TRUST_RELEASE_SIGNATURE_URL}" "${TRUST_PUBLIC_KEY_FILE}" "${STAGE_DIR}/trust-config.js" <<'PY'
import json
import sys
from pathlib import Path

manifest_url, signature_url, public_key_file, output = sys.argv[1:]
public_key = Path(public_key_file).read_text()
config = {
    "releaseManifestUrl": manifest_url,
    "releaseSignatureUrl": signature_url,
    "publicKeyPem": public_key,
}
Path(output).write_text(
    "// Generated by scripts/package-served-files.sh.\n"
    "window.SINGULAR_WORKBENCH_TRUST = "
    + json.dumps(config, indent=2)
    + ";\n"
)
PY
fi

METADATA=(
  --metadata "releaseId=${RELEASE_ID}"
)
if [[ -n "${SERVER_BASE_URL}" ]]; then
  METADATA+=(--metadata "serverBaseUrl=${SERVER_BASE_URL}")
fi
if [[ -n "${GITHUB_MANIFEST_URL}" ]]; then
  METADATA+=(--metadata "githubManifestUrl=${GITHUB_MANIFEST_URL}")
fi
if git -C "${WORKBENCH_DIR}/../.." rev-parse HEAD >/dev/null 2>&1; then
  METADATA+=(--metadata "gitCommit=$(git -C "${WORKBENCH_DIR}/../.." rev-parse HEAD)")
fi

ASSET_ARGS=()
for asset in "${RUNTIME_ASSETS[@]}"; do
  ASSET_ARGS+=(--asset "${asset}")
done

python3 "${WORKBENCH_DIR}/scripts/write-asset-manifest.py" \
  --base "${STAGE_DIR}" \
  --output "${OUT_DIR}/release-manifest.json" \
  --name "Singular WebAssembly browser release" \
  --source "Singular Online release package" \
  "${METADATA[@]}" \
  "${ASSET_ARGS[@]}"

if [[ -n "${SIGNING_KEY}" ]]; then
  node "${WORKBENCH_DIR}/scripts/sign-release-manifest.mjs" \
    --key "${SIGNING_KEY}" \
    --manifest "${OUT_DIR}/release-manifest.json" \
    --signature "${OUT_DIR}/release-manifest.json.sig"
fi

ZIP_PATH="${OUT_DIR}/singular-workbench-${RELEASE_ID}.zip"
rm -f "${ZIP_PATH}"
(
  cd "${STAGE_DIR}"
  zip -9 "${ZIP_PATH}" "${RUNTIME_ASSETS[@]}"
)

cat <<MSG
Release package written to:
  ${ZIP_PATH}

Release manifest:
  ${OUT_DIR}/release-manifest.json

MSG
if [[ -f "${OUT_DIR}/release-manifest.json.sig" ]]; then
  cat <<MSG
Release signature:
  ${OUT_DIR}/release-manifest.json.sig
  ${OUT_DIR}/release-manifest.json.sig.base64

MSG
fi
